apiVersion: v1
kind: Service
metadata:
  name: weather-service
  # namespace: default #comment this cause it will be defined in run command with kustomize
spec:
  type: ClusterIP # also will not expose to outside world
  selector:
    app: weather-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000