
# we won't do any thing here except doing serve static fiels from /usr/share/nginx/html 
# reverse proxy (Routing)done now by ingress
# tls termination done now by ingress
# load balalncer done now by service
# if this app ws react app but this not react this express node with some static files 
server{
    listen 80; 
    server_name localhost;

    location / {

        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

}

